name = "email-sender"
main = "src/index.ts"
compatibility_date = "2024-06-13"

[vars]
SENDER_EMAIL = "sandbox@sendgrid.net"
API_KEY = "123456"


[[d1_databases]]
binding = "DB"
database_name = "db-correos-ac"
database_id = "ee138b48-d943-4846-ba3f-e9b3f53eb728"